app = 'job-hunt-bot'
primary_region = 'fra'

[build]

[env]
  NODE_ENV = 'production'

[processes]
  app = 'node src/index.js'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
